export enum StatusAPICode {
  code = "code",
  hashing_password = 100,
  sign_in_request = 101,
  GET_EMPLOYEE_DETAILS = 102,
  UPDATE_APPLICABLE_SUBSIDY = 103,
  GET_CHECK_EMPLOYEE_ID = 104,
  GET_DEPARTMENT_LISTS = 105,
  CREATE_EMPLOYEE = 106,
  UPDATE_EMPLOYEE = 107,
  CREATE_SUBSIDY_TRANSACTION = 108,

}
